### ISSUE TITLE
Received "Field 'host' not present." error.

### ISSUE THREAD

**Issue by kengsenghor** [Nyaran/testlink-xmlrpc#1]
Hi,

I have installed this testlink-xmlrpc NPM package on my NodeJS environment. When running the codes (using the sample implementation), below error is received:
`E/launcher - Error: Error: Field 'host' not present.`

**Comment by Nyaran** [comment]
Hi. First at all, thanks for using the module.

I confirmed the issue, I'll try to fix it soon as possible, but now I'm at work, so, please, wait a bit.

**Comment by kengsenghor** [comment]
Thanks!
