### ISSUE TITLE
How can I find testcase id and testplan id?

### ISSUE THREAD

**Issue by barddoo** [Nyaran/testlink-xmlrpc#12]
I've trying to find those ids in TestLink but I haven't anywhere.

**Comment by Nyaran** [comment]
If your question is about the Web interface, please, go to TestLink documentation and it issue tracker.

If you are asking to obtain it with using the API through this client, you can get the Test Case ID with this method: **_getTestCaseIDByName_** - You need to know the exact name

To get the Test Plan Id, you can get the entire Test Plan object with the method: **_getTestPlanByName_** - Also you need to know the exact name.
