### ISSUE TITLE
Update test suite does not work

### ISSUE THREAD

**Issue by quan612** [Nyaran/testlink-xmlrpc#13]
Hi,

 I tried using testlink version 1.9.15 and 1.9.19 (the latest on Bitnami).  I am a bit lost as i am not sure if it relates to this api or due to the api on Testlink server.

testLink.updateTestSuite ({
        testprojectid: props.selectedProject.id, //projectId        
        testsuitename: suiteName, //name of test suite
        details: "suiteDetails",
        parentid: props.testItemDetails.id,  //the parent suite of this suite
        order: 4
});

On 1.9.15 i got an exception error, i think it may be due to an error in the testlink server. When i tried using the 1.9.19, the api ran file, there was no error but the test suite is not updated. Here I tried to catch the result of the promise.

![image](https://user-images.githubusercontent.com/14017471/65011923-5bc00f00-d8e3-11e9-8e49-5931fb66c6be.png)

Here is how the Create Test Suite api ran - which was fine 

![image](https://user-images.githubusercontent.com/14017471/65011956-7abea100-d8e3-11e9-9291-1b627bd41c29.png)

**Comment by liyinchigithub** [comment]
me too
