### ISSUE TITLE
Error: getaddrinfo ENOTFOUND received

### ISSUE THREAD

**Issue by kengsenghor** [Nyaran/testlink-xmlrpc#2]
Using testlink-xmlrpc@1.9.18-2 version, error received with following codes.

```js
const TestLink = require('testlink-xmlrpc');

let testlink = new TestLink({
    host: "http://mytestlink",
    rpcPath: "testlink/lib/api/xmlrpc/v1/xmlrpc.php",
    secure: false, // Use https, if you are using http, set to false.
    apiKey: "<the_api_key>", // The API KEY from TestLink. Get it from user profile.
});

async function checkConnection() {
    let ping = await testlink.sayHello();
    if (ping === "Hello!")
        console.log("connection established");
}

testlink.checkDevKey({devKey: 'APIKEY_to_check'}).then(reply => {
    if (reply === true)
        console.log("API KEY is valid");
    else
        console.log("API KEY is invalid");
});
```

> (node:29302) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND http://mytestlink http://mytestlink:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

**Comment by kengsenghor** [comment]
The TestLink login page for my setup is 

> http://mytestlink/testlink/login.php

**Comment by Nyaran** [comment]
Hi, you missed out the beginning slash in rpcPath

```javascript
let testlink = new TestLink({
    host: "http://mytestlink",
    rpcPath: "/testlink/lib/api/xmlrpc/v1/xmlrpc.php",
    secure: false, // Use https, if you are using http, set to false.
    apiKey: "<the_api_key>", // The API KEY from TestLink. Get it from user profile.
});
```

**Comment by kengsenghor** [comment]
Alright. Now seems working but I got below error.

> (node:5523) UnhandledPromiseRejectionWarning: [2000] (checkDevKey) - Can not authenticate client: invalid developer key

**Comment by Nyaran** [comment]
replace the value on "apiKey" with a valid apiKey

**Comment by kengsenghor** [comment]
After rechecked the codes,
Need to change from 'APIKEY_to_check' to actual key value and issue resolved.
`testlink.checkDevKey({devKey: 'APIKEY_to_check'}).then(reply => {`

Output:
Jasmine started

Executed 0 of 0 specs SUCCESS in 0.013 sec.
API KEY is valid

**Comment by Nyaran** [comment]
Nice. If you have any other problem, please open a new issue.

**Comment by kengsenghor** [comment]
Sure Nyaran, thanks!

**Comment by Charl3jr** [comment]
> Alright. Now seems working but I got below error.
> 
> > (node:5523) UnhandledPromiseRejectionWarning: [2000] (checkDevKey) - Can not authenticate client: invalid developer key
> 
> The API key was generated via 'My Settings', Under API interface, click 'Generate new key'.
> And, under config.inc.php from TestLink, this configuration is enabed
> `$tlCfg->api->enabled = TRUE;`

I am handle this issue as well, where can I find `$tlCfg->api->enabled = TRUE;`?

**Comment by Nyaran** [comment]
Please, avoid to write on closed tickets.

Anyway, that file is in TestLink folder, on your webserver.
