### ISSUE TITLE
Received Error: Field 'executiontype' not present.

### ISSUE THREAD

**Issue by kengsenghor** [Nyaran/testlink-xmlrpc#3]
Nyaran,

### UPDATED MESSAGE CONTENTS:
After I'd created test case with below codes:
```js
testlink.createTestCase({
    testcasename: "Test Case #5", // Test Case name.
    testsuiteid: 851, // TestSuite id in TestLink.
    testprojectid: 850, // Project id in TestLink.
    status: 3,
    importance: 3,
    execution: 2,
    authorlogin: "ks", // Author of Test Case.
    summary: "This Test Case is an example created from TestLink API", // Test Case description.
    steps: [{
    	step_number: 1,
    	actions: "Action 1",
    	execution_type: 2
    }] // Array containing the Test Case steps.
});
```
Then, I tried to update test case execution type, as follows:
```js
testlink.setTestCaseExecutionType({
	testcaseexternalid: 4,
	version: 1,
	testprojectid: 850,
	executiontype: 2
});
```

**Comment by Nyaran** [comment]
> About setTestCaseExecutionType (First message)
testcaseexternalid: This MUST include the project prefix. (TestLink requirement)

> About executiontype & execution_type (Second message)
- executiontype (without underscore):Belongs to Test Case object 
- execution_type (with underscore): Belongs to the Steps object (contained in Test Case)

**Comment by kengsenghor** [comment]
Cool. It is working now. 

When I update executiontype, I also want to update execution_type but not the way currently doing for setTestCaseExecutionType function.

**Comment by Nyaran** [comment]
I think you must set the execution type for Test Case and for each step inside. This is how TestLink works.

BTW, you can include the constants file to use it easly

```javascript
const constants = require('testlink-xmlrpc/lib/constants');

testlink.createTestCase({
 ...
	executiontype: constants.ExecutionType.AUTOMATED,
 ...
});

**Comment by kengsenghor** [comment]
Thanks! I will try this out later. My question was if we update executiontype, in each step should also update to what had been set in executiontype for steps[].execution_type, agree? Or, at least this setTestCaseExecutionType function capable to also handle steps[].execution_type optional?

**Comment by kengsenghor** [comment]
There is one option called "Apply To All Steps" on the Test Case GUI. Could setTestCaseExecutionType function include this option whenever there is update on executiontype, it also able to alter all steps execution_type by enable this "Apply To All Steps" option?

**Comment by Nyaran** [comment]
I think there is not an option like that exposed on TestLink API (https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php)

Anyway I will study to implemented useful functions like that on the future.
