### ISSUE TITLE
Received Error: Field '0' not present.

### ISSUE THREAD

**Issue by kengsenghor** [Nyaran/testlink-xmlrpc#5]
When trying to execute below code snippets,
```js
testlink.reportTCResult({
    testcaseexternalid: "XXX-1",
    status: constants.ExecutionStatus.PASSED,
    steps: [{
    	step_number: 1,
    	result: constants.ExecutionStatus.PASSED,
    	notes: "note for passed test case."
    }]
});
```
Below error is received.
`E/launcher - Error: Error: Field '0' not present.`

**Comment by Nyaran** [comment]
Good catch, fixed.

**Comment by kengsenghor** [comment]
Thanks for the fixed. Now received missing the following options when calling reportTCResult().

- testplanid

- buildid

Same goes for setTestCaseExecutionResult(). Include those options will fix the problems.
