### ISSUE TITLE
Only last execution notes and execution status is being reported

### ISSUE THREAD

**Issue by kengsenghor** [Nyaran/testlink-xmlrpc#9]
Using reportTCResult() API, when a particular test case being executed, say, contained 3 test steps. For example, when the test reached step 3 and test result is success on all steps, only last step will report the execution notes and execution status, but for step 1 and 2, nothing is reported.

I am expect that each test step shall report the information which implemented using that API.

**Comment by Nyaran** [comment]
Hi,
Are you including all the steps in the request?

`javascript
testlink.reportTCResult({
    testcaseexternalid: "MF-1",
    testplanid: 354,
    buildid: 7,
    status: constants.ExecutionStatus.FAILED,
    steps: [
        {
            step_number: 1,
            result: constants.ExecutionStatus.PASSED,
            notes: "note for passed test case."
        },
        {
            step_number: 2,
            result: constants.ExecutionStatus.FAILED,
            notes: "note for failed test case 2."
        },
        {
            step_number: 3,
            result: constants.ExecutionStatus.BLOCKED,
            notes: "note for blocked test case333."
        }]
})
`

**Comment by kengsenghor** [comment]
I did those steps separately. Thanks for the example codes, let me try it out later.

**Comment by Nyaran** [comment]
Did you mean, that if you have 3 steps, you are calling **reportTCResult** 3 times? Thats wrong, and if you look on report view click "Show complete execution history" you will see all the executions.

**Comment by kengsenghor** [comment]
My previous codes design were called reportTCResult() for each single step, so it will be 3 calling in total for 3 steps for instance. But, I have modified the codes accordingly now to have all steps in one reportTCResult() that required update, and tested fine.
